### ISSUE TITLE
suggestions for catalog updates

### ISSUE THREAD

**Issue by tomkralidis** [WCGA/knowledge-base#3]
On page http://wcodp.readthedocs.org/catalogs/catalogs.html, suggest:
- change PyCSW to pycsw
- suggestions for pycsw sites (more exhaustive list at https://github.com/geopython/pycsw/wiki/Live-Deployments)
  - Pacific Islands Ocean Observing System (PacIOOS) (http://pacioos.org/)
  - data.gov (http://data.gov)
  - Land Information New Zealand (https://data.linz.govt.nz/) 

Awesome resource -- keep up the good work!

**Comment by tomkralidis** [comment]
sorry forget to cc @cybersea here.

**Comment by cybersea** [comment]
Thanks for the helpful feedback @tomkralidis.  Updated catalogs.html per your suggestions.   (except for leaving data.gov in the CKAN section).
